=== Elfpope/web-service-development-vehicle-management-system/WebContent/WEB-INF/trips.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="wsdVehicleMgmtSystem/trips" xmlns="wsdVehicleMgmtSystem/trips"
	elementFormDefault="qualified">

	<!-- Type declarations -->
	<xs:simpleType name="regoNumber">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z]{3}[0-9]{3}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="Name">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z][a-zA-Z]* [A-Z][a-zA-Z]*" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="Date">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d{1,2}/\d{1,2}/\d{1,4}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="Time">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-2]{0,1}[0-9]:[0-5]{0,1}[0-9]" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="positiveDecimal">
		<xs:restriction base="xs:decimal ">
			<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="trip">
		<xs:sequence>
			<xs:element name="regoNumber" type="regoNumber" />
			<xs:element name="driverId" type="xs:string" />
			<xs:element name="driverName" type="Name" />
			<xs:element name="startDate" type="Date" />
			<xs:element name="startTime" type="Time" />
			<xs:element name="endDate" type="Date" />
			<xs:element name="endTime" type="Time" />
			<xs:element name="description" type="xs:string" />
			<xs:element name="kilometres" type="positiveDecimal" />
			<xs:element name="deleted" type="xs:boolean" />
			<xs:element name="deletedById" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<!-- xml structure -->
	<xs:element name="trips">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="trip" type="trip" minOccurs="0"
					maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== Elfpope/web-service-development-vehicle-management-system/WebContent/WEB-INF/trips.xml
<?xml version="1.0" encoding="UTF-8"?>
<trips xmlns="wsdVehicleMgmtSystem/trips" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="wsdVehicleMgmtSystem/trips trips.xsd">
<!-- Wondering if having trips separated into a single xml could enhence 
	object-oriented programming -->

	<trip>
		<regoNumber>ABC123</regoNumber>
		<driverId>D1000</driverId>
		<driverName>David Kim</driverName>
		<startDate>01/08/2014</startDate>
		<startTime>8:00</startTime>
		<endDate>05/08/2014</endDate>
		<endTime>20:00</endTime>
		<description>Commute staff between offices</description>
		<kilometres>1000</kilometres>
		<deleted>false</deleted>
		<deletedById></deletedById>
	</trip>
	<trip>
		<regoNumber>ABC123</regoNumber>
		<driverId>J1000</driverId>
		<driverName>James Pan</driverName>
		<startDate>08/08/2014</startDate>
		<startTime>9:00</startTime>
		<endDate>15/08/2014</endDate>
		<endTime>21:00</endTime>
		<description>Carry stuff between offices</description>
		<kilometres>1500</kilometres>
		<deleted>false</deleted>
		<deletedById></deletedById>
	</trip>
	<trip>
		<regoNumber>EFG123</regoNumber>
		<driverId>G1000</driverId>
		<driverName>Gorden Green</driverName>
		<startDate>01/08/2014</startDate>
		<startTime>10:00</startTime>
		<endDate>03/08/2014</endDate>
		<endTime>20:00</endTime>
		<description>travel to Canberra</description>
		<kilometres>1200</kilometres>
		<deleted>false</deleted>
		<deletedById></deletedById>
	</trip>
	<trip>
		<regoNumber>EFG123</regoNumber>
		<driverId>J1000</driverId>
		<driverName>James Pan</driverName>
		<startDate>05/08/2014</startDate>
		<startTime>9:00</startTime>
		<endDate>15/08/2014</endDate>
		<endTime>21:00</endTime>
		<description>travel to Brisbane</description>
		<kilometres>1500</kilometres>
		<deleted>false</deleted>
		<deletedById></deletedById>
	</trip>
	<trip>
		<regoNumber>HJK123</regoNumber>
		<driverId>G1000</driverId>
		<driverName>Gorden Green</driverName>
		<startDate>07/08/2014</startDate>
		<startTime>10:00</startTime>
		<endDate>13/08/2014</endDate>
		<endTime>20:00</endTime>
		<description>travel to BlueMountain</description>
		<kilometres>1200</kilometres>
		<deleted>false</deleted>
		<deletedById></deletedById>
	</trip>
	<trip>
		<regoNumber>HJK123</regoNumber>
		<driverId>D1000</driverId>
		<driverName>David Kim</driverName>
		<startDate>15/08/2014</startDate>
		<startTime>9:00</startTime>
		<endDate>18/08/2014</endDate>
		<endTime>21:00</endTime>
		<description>travel to Canberra</description>
		<kilometres>1500</kilometres>
		<deleted>false</deleted>
		<deletedById></deletedById>
	</trip>
	<trip>
		<regoNumber>XYZ789</regoNumber>
		<driverId>J1000</driverId>
		<driverName>James Pan</driverName>
		<startDate>03/08/2014</startDate>
		<startTime>10:00</startTime>
		<endDate>7/08/2014</endDate>
		<endTime>20:00</endTime>
		<description>Commute staff between offices</description>
		<kilometres>800</kilometres>
		<deleted>false</deleted>
		<deletedById></deletedById>
	</trip>
	<trip>
		<regoNumber>XYZ789</regoNumber>
		<driverId>G1000</driverId>
		<driverName>Gorden Green</driverName>
		<startDate>12/08/2014</startDate>
		<startTime>9:00</startTime>
		<endDate>17/08/2014</endDate>
		<endTime>21:00</endTime>
		<description>travel to Brisbane</description>
		<kilometres>1500</kilometres>
		<deleted>false</deleted>
		<deletedById></deletedById>
	</trip>
</trips>
